name: Unzip ZIP File and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Show files before unzip
        run: ls -la

      - name: Unzip arsynox-mail-cloudflare.zip
        run: |
          unzip -o arsynox-mail-cloudflare.zip -d extract

      - name: Show files after unzip
        run: ls -la extract 
      - name: Commit extract files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add extract
          git commit -m "Auto: unzip arsynox-mail-cloudflare.zip" || echo "Nothing to commit"
          git push
